from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List


def load_rows(path: Path) -> List[Dict[str, Any]]:
    with path.open("r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        rows = []
        for row in reader:
            rows.append(
                {
                    "case": row["case"],
                    "tag": row["tag"],
                    "num_observation": int(row["num_observation"]),
                    "noise_std": float(row["noise_std"]),
                    "rel_l2": float(row["rel_l2"]),
                    "reliability_raw": float(row["reliability_raw"]),
                    "physics_rms": float(row["physics_rms"]),
                    "boundary_rms": float(row["boundary_rms"]),
                    "structure_error": float(row["structure_error"]),
                }
            )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze coarse boundary sweep results.")
    parser.add_argument(
        "--input-csv",
        default="minimal_pinn/results/boundary_sweep_summary.csv",
        help="Path to the summary CSV generated by sweep_boundary.py",
    )
    parser.add_argument(
        "--output-json",
        default="minimal_pinn/results/boundary_analysis.json",
        help="Path to save the boundary analysis JSON.",
    )
    parser.add_argument(
        "--degradation-factor",
        type=float,
        default=1.5,
        help="Boundary is first point whose rel_l2 exceeds baseline * factor.",
    )
    args = parser.parse_args()

    rows = load_rows(Path(args.input_csv))
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[row["case"]].append(row)

    analysis: Dict[str, Any] = {}
    for case_name, case_rows in grouped.items():
        baseline = next(row for row in case_rows if row["tag"] == "baseline")
        ordered = sorted(
            [row for row in case_rows if row["tag"] != "baseline"],
            key=lambda row: (row["num_observation"], row["noise_std"]),
        )
        boundary = None
        for row in ordered:
            if row["rel_l2"] >= baseline["rel_l2"] * args.degradation_factor:
                boundary = row
                break
        analysis[case_name] = {
            "baseline": baseline,
            "degradation_factor": args.degradation_factor,
            "boundary_candidate": boundary,
            "all_rows": ordered,
        }

    output_path = Path(args.output_json)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        json.dump(analysis, fh, ensure_ascii=False, indent=2)
    print(f"[done] analysis_json={output_path}")
    print(json.dumps(analysis, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
